[package]
name = "log-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.12", features = ["json", "multipart"] }
serenity = "0.12.4"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
