name: Build And Push Container Image
on:
  push:
    branch: master
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Lowercase github.repository
      id: lowercase
      run: echo "::set-output name=value::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
    - name: Build and Push Container
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ghcr.io/${{ steps.lowercase.outputs.value }}:latest
